// <auto-generated />
using System;
using ApplicantPersonalAccount.Persistence.Contextes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApplicantPersonalAccount.Persistence.Migrations.Application
{
    [DbContext(typeof(ApplicationDataContext))]
    [Migration("20250425064639_Enterance")]
    partial class Enterance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApplicantPersonalAccount.Persistence.Entities.ApplicationDb.EnteranceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Enterances");
                });

            modelBuilder.Entity("ApplicantPersonalAccount.Persistence.Entities.ApplicationDb.EnteranceProgramEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EnteranceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EnteranceId");

                    b.ToTable("EnterancePrograms");
                });

            modelBuilder.Entity("ApplicantPersonalAccount.Persistence.Entities.ApplicationDb.SignedToNotificationsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SigningTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("SignedToNotifications");
                });

            modelBuilder.Entity("ApplicantPersonalAccount.Persistence.Entities.ApplicationDb.EnteranceProgramEntity", b =>
                {
                    b.HasOne("ApplicantPersonalAccount.Persistence.Entities.ApplicationDb.EnteranceEntity", "Enterance")
                        .WithMany("Programs")
                        .HasForeignKey("EnteranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enterance");
                });

            modelBuilder.Entity("ApplicantPersonalAccount.Persistence.Entities.ApplicationDb.EnteranceEntity", b =>
                {
                    b.Navigation("Programs");
                });
#pragma warning restore 612, 618
        }
    }
}
